### ISSUE TITLE
Reference link on page redirects to indecent NSFW website without an useful information

### ISSUE THREAD

**Issue by neortls007idev** [ikrima/gamedevguide#13]
On this page https://ikrima.dev/ue4guide/build-guide/build-target-file-demystified/ the first link http://dmitry-yanovsky.com/2015/08/unreal-engine-4-build-file-demystified seems to have been redirected to an indecent NSFW website.

**Comment by ikrima** [comment]
Thanks for the heads up! Fixed with https://github.com/ikrima/gamedevguide/commit/ea1782624315e715ab36d099101944122e15a245
