### ISSUE TITLE
Programmatically feeding UE's reflection system?

### ISSUE THREAD

**Issue by notdanilo** [ikrima/gamedevguide#18]
I just found your article about the reflection system and it's a good starting point for a research I am doing for making Rust available in UE. I just would like to ask you: Do you know if there is any way to programmatically feed the reflection system? Something like this:

```cpp
UCLASS()
class AExample : public AActor
{
	GENERATED_BODY()	
public:
	AExample ();

	// THIS IS COMMENTED OUT UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Speed = 1.0f;
};

AExample::AExample() {
  ReflectionSystem::AddProperty(&Speed, "EditAnywhere, BlueprintReadWrite");
}
```

**Comment by ikrima** [comment]
It is possible and I vaguely recall writing it up some notes on that but they're probably very messy and in the unfinished section.

A good starting point is looking at the builtin python integration or the (deprecated) community python plugin.

**Comment by ikrima** [comment]
For low-level learning purposes, you can always build the project and look at the UHT generated header and class files. If you emulate those manually, you can see how the reflection system is constructed/fed.


_usual caveat of course,_ whether you can; whether you should is another matter
